name: zizmor GitHub Actions static analysis
on:
  push:
    
jobs:
  zizmor-check:
    name: Check whether there are things to scan
    permissions:
      contents: read
    runs-on: ${{ !github.event.repository.private && 'ubuntu-latest' || 'ubuntu-arm64-small' }}
    outputs:
      found-files: ${{ steps.zizmor-check.outputs.found-files }}
    steps:
    - name: Get secrets from Vault
      id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@f1614b210386ac420af6807a997ac7f6d96e477a # get-vault-secrets/v1.3.1
      env:
        ACTIONS_ID_TOKEN_REQUEST_TOKEN: abc
        ACTIONS_ID_TOKEN_REQUEST_URL: def
        VAULT_INSTANCE: ops
      with:
        vault_instance: ops
        common_secrets: |
          NFPM_SIGNING_KEY=packages-gpg:private-key
          GITHUB_APP_ID=plugins-platform-bot-app:app-id
          GITHUB_APP_PRIVATE_KEY=plugins-platform-bot-app:private-key
        export_env: false
    - name: Check for files to scan
      id: foo
      run: |
        env | rev